### PR TITLE
code restructured

### PR DESCRIPTION
**Pull request by aaron-fredrick**
# code restructured

* code restructured into functions for the fibonacci function added the caching decorator, so it functions smoothly similar to the previous while loop implementation

* Made a function called main to parse the input into int and catch errors

* main function called in `if __name__ == "__main__"`, which also allows user to understand that this scripts is to be called in execution (python ways)

### CODE REVIEW

**Comment by Rashini2001** [comment]
hi

**Comment by aaron-fredrick** [comment]
hi, i came across your code and with my interest in maths and python programming i decided to do a code restructure to a more organize structure in python coding standard, and it seems like you have already merge my pull request 

happy coding 😊

**Comment by Rashini2001** [comment]
hii good evening.
thankyouu so much. When will the next task be given?

**Comment by aaron-fredrick** [comment]
I dont do task giving and im confused, im simply giving contributions to repos i come across
and please dont use pull request comments as communications, if you like my contribution feel free to reach me via linked in email (mentioned in my github profile page)
Thankyou

**Pull request merged**
